services:
  postgres:
    image: postgres:latest
    container_name: go-bootiful-ordering-postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: orders
    ports:
      - "5432:5432"
    volumes:
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d orders"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    container_name: go-bootiful-ordering-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  tempo:
    image: grafana/tempo:latest
    container_name: go-bootiful-ordering-tempo
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
    ports:
      - "3200:3200"  # tempo
      - "4317:4317"  # otlp grpc
      - "4318:4318"  # otlp http
      - "9411:9411"  # zipkin
      - "6831:6831/udp" # jaeger thrift compact
      - "6832:6832/udp" # jaeger thrift binary
      - "14268:14268" # jaeger http

  prometheus:
    image: prom/prometheus:latest
    container_name: go-bootiful-ordering-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:9090/-/healthy"]
      interval: 10s
      timeout: 5s
      retries: 5

  pyroscope:
    image: pyroscope/pyroscope:latest
    container_name: go-bootiful-ordering-pyroscope
    ports:
      - "4040:4040"
    command:
      - "server"
    volumes:
      - pyroscope-data:/var/lib/pyroscope
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:4040/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  grafana:
    image: grafana/grafana:latest
    container_name: go-bootiful-ordering-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - prometheus
      - pyroscope
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:3000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  order:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-bootiful-ordering-order
    command: ["./bin/order"]
    ports:
      - "8082:8082"
      - "9092:9092"
    volumes:
      - ./config:/app/config
    depends_on:
      - postgres
      - tempo
      - prometheus
      - pyroscope
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  product:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-bootiful-ordering-product
    command: ["./bin/product"]
    ports:
      - "8081:8081"
      - "9091:9091"
    volumes:
      - ./config:/app/config
    depends_on:
      - postgres
      - redis
      - tempo
      - prometheus
      - pyroscope
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8081/health"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  grafana-storage:
  pyroscope-data:
