version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: go-bootiful-ordering-postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: orders
    ports:
      - "5432:5432"
    volumes:
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d orders"]
      interval: 10s
      timeout: 5s
      retries: 5
