global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'order-service'
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          service: 'order-service'

  - job_name: 'product-service'
    static_configs:
      - targets: ['host.docker.internal:8081']
        labels:
          service: 'product-service'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          service: 'prometheus'