# Order service configuration
service:
  name: order-service

# Database configuration
db:
  host: localhost
  port: "5432"
  user: myuser
  password: secret
  name: orders
  sslMode: disable

# Jaeger configuration (kept for backward compatibility)
jaeger:
  host: localhost
  port: "6831"
  logSpans: true

# Tempo configuration
tempo:
  host: localhost
  port: "6831"
  logSpans: true

# Pyroscope configuration
pyroscope:
  host: localhost
  port: "4040"

# Server configuration
server:
  http:
    port: "8084"
  grpc:
    port: "9094"
