# Product service configuration
service:
  name: product-service

# Database configuration
db:
  host: localhost
  port: "5432"
  user: myuser
  password: secret
  name: products
  sslMode: disable

# Redis configuration
redis:
  host: localhost
  port: "6379"
  password: ""
  db: 0

# Jaeger configuration
jaeger:
  host: localhost
  port: "6831"
  logSpans: true

# Server configuration
server:
  http:
    port: "8081"
  grpc:
    port: "9091"
