# Product service configuration
service:
  name: product-service

# Database configuration
db:
  host: localhost
  port: "5432"
  user: myuser
  password: secret
  name: products
  sslMode: disable

# Redis configuration
redis:
  host: localhost
  port: "6379"
  password: ""
  db: 0

# Jaeger configuration (kept for backward compatibility)
jaeger:
  host: localhost
  port: "6831"
  logSpans: true

# Tempo configuration
tempo:
  host: localhost
  port: "6831"
  logSpans: true

# Pyroscope configuration
pyroscope:
  host: localhost
  port: "4040"

# Server configuration
server:
  http:
    port: "8083"
  grpc:
    port: "9093"
